// lib/country-lang-map.ts

/** خريطة لغات افتراضية للدولة كمحفّظ (fallback) */
export const COUNTRY_LANG_MAP: Record<string, string> = {
  Afghanistan: "fa",
  Albania: "sq",
  Algeria: "ar",
  Andorra: "ca",
  Angola: "pt",
  "Antigua and Barbuda": "en",
  Argentina: "es",
  Armenia: "hy",
  Australia: "en",
  Austria: "de",
  Azerbaijan: "az",
  Bahamas: "en",
  Bahrain: "ar",
  Bangladesh: "bn",
  Barbados: "en",
  Belarus: "be",
  Belgium: "fr",
  Belize: "en",
  Benin: "fr",
  Bhutan: "dz",
  Bolivia: "es",
  "Bosnia and Herzegovina": "bs",
  Botswana: "en",
  Brazil: "pt",
  Brunei: "ms",
  Bulgaria: "bg",
  "Burkina Faso": "fr",
  Burundi: "fr",
  "Cabo Verde": "pt",
  Cambodia: "km",
  Cameroon: "fr",
  Canada: "en",
  "Central African Republic": "fr",
  Chad: "fr",
  Chile: "es",
  China: "zh",
  Colombia: "es",
  Comoros: "fr",
  "Congo (Brazzaville)": "fr",
  "Congo (Kinshasa)": "fr",
  "Costa Rica": "es",
  "Côte d'Ivoire": "fr",
  "Cote d'Ivoire": "fr",
  Croatia: "hr",
  Cuba: "es",
  Cyprus: "el",
  "Czech Republic": "cs",
  Denmark: "da",
  Djibouti: "fr",
  Dominica: "en",
  "Dominican Republic": "es",
  Ecuador: "es",
  Egypt: "ar",
  "El Salvador": "es",
  "Equatorial Guinea": "es",
  Eritrea: "ti",
  Estonia: "et",
  Eswatini: "en",
  Ethiopia: "am",
  Fiji: "en",
  Finland: "fi",
  France: "fr",
  Gabon: "fr",
  Gambia: "en",
  Georgia: "ka",
  Germany: "de",
  Ghana: "en",
  Greece: "el",
  Grenada: "en",
  Guatemala: "es",
  Guinea: "fr",
  "Guinea-Bissau": "pt",
  Guyana: "en",
  Haiti: "fr",
  Honduras: "es",
  Hungary: "hu",
  Iceland: "is",
  India: "hi",
  Indonesia: "id",
  Iran: "fa",
  Iraq: "ar",
  Ireland: "en",
  Israel: "he",
  Italy: "it",
  Jamaica: "en",
  Japan: "ja",
  Jordan: "ar",
  Kazakhstan: "kk",
  Kenya: "sw",
  Kiribati: "en",
  Kuwait: "ar",
  Kyrgyzstan: "ky",
  Laos: "lo",
  Latvia: "lv",
  Lebanon: "ar",
  Lesotho: "en",
  Liberia: "en",
  Libya: "ar",
  Liechtenstein: "de",
  Lithuania: "lt",
  Luxembourg: "fr",
  Madagascar: "fr",
  Malawi: "en",
  Malaysia: "ms",
  Maldives: "dv",
  Mali: "fr",
  Malta: "en",
  "Marshall Islands": "en",
  Mauritania: "ar",
  Mauritius: "en",
  Mexico: "es",
  Micronesia: "en",
  Moldova: "ro",
  Monaco: "fr",
  Mongolia: "mn",
  Montenegro: "sr",
  Morocco: "ar",
  Mozambique: "pt",
  Myanmar: "my",
  Namibia: "en",
  Nauru: "en",
  Nepal: "ne",
  Netherlands: "nl",
  "New Zealand": "en",
  Nicaragua: "es",
  Niger: "fr",
  Nigeria: "en",
  "North Korea": "ko",
  "North Macedonia": "mk",
  Norway: "no",
  Oman: "ar",
  Pakistan: "ur",
  Palau: "en",
  Panama: "es",
  "Papua New Guinea": "en",
  Paraguay: "es",
  Peru: "es",
  Philippines: "en",
  Poland: "pl",
  Portugal: "pt",
  Qatar: "ar",
  Romania: "ro",
  Russia: "ru",
  Rwanda: "rw",
  "Saint Kitts and Nevis": "en",
  "Saint Lucia": "en",
  "Saint Vincent and the Grenadines": "en",
  Samoa: "sm",
  "San Marino": "it",
  "Sao Tome and Principe": "pt",
  "Saudi Arabia": "ar",
  Senegal: "fr",
  Serbia: "sr",
  Seychelles: "en",
  "Sierra Leone": "en",
  Singapore: "en",
  Slovakia: "sk",
  Slovenia: "sl",
  "Solomon Islands": "en",
  Somalia: "so",
  "South Africa": "en",
  "South Korea": "ko",
  "South Sudan": "en",
  Spain: "es",
  "Sri Lanka": "si",
  Sudan: "ar",
  Suriname: "nl",
  Sweden: "sv",
  Switzerland: "de",
  Syria: "ar",
  Taiwan: "zh",
  Tajikistan: "tg",
  Tanzania: "sw",
  Thailand: "th",
  "Timor-Leste": "pt",
  Togo: "fr",
  Tonga: "en",
  "Trinidad and Tobago": "en",
  Tunisia: "ar",
  Turkey: "tr",
  Turkmenistan: "tk",
  Tuvalu: "en",
  Uganda: "en",
  Ukraine: "uk",
  "United Arab Emirates": "ar",
  "United Kingdom": "en",
  "United States of America": "en",
  "United States": "en",
  Uruguay: "es",
  Uzbekistan: "uz",
  Vanuatu: "en",
  "Vatican City": "it",
  Venezuela: "es",
  Vietnam: "vi",
  Yemen: "ar",
  Zambia: "en",
  Zimbabwe: "en",
}